project:
  type: website
  output-dir: _site
theme: lux
format:
  html:
    code-fold: true
    theme:
      light: [lux, https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap]
      dark: [lux, https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap]
    css: styles/styles.css
# Navigation structure
website:
  title: "pyOpenSci metrics"
  site-url: "https://www.pyopensci.org"
  repo-url: "https://www.github.com/pyopensci/metrics"
  favicon: images/favicon.ico
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Peer Review"
        menu:
          - text: Peer Review Status Dashboard
            href: peer-review/peer-review-status-dashboard.qmd
          - text: Editorial Dashboard
            href: peer-review/editorial-dashboard.qmd
          - text: Current Review Status
            href: peer-review/current-review-status.qmd
          - text: Over Time 
            href: peer-review/reviews-over-time.qmd
          - text: Peer review trends
            href: peer-review/review-trends.qmd

      - text: "pyOpenSci Packages"
        menu:
          - text: Package Activity Dashboard
            href: pyos-packages/package-activity.qmd
          - text: Accepted Package Metrics
            href: peer-review/accepted-packages.qmd
          - text: Package Dashboard
            href: peer-review/pyos-package-dashboard.qmd


      - text: "Contributors"
        menu:
          - text: Contributor Data
            href: contributors/contributors.qmd
          - text: Sprint Data
            href: contributors/sprints.qmd


    right:
      - icon: github
        href: https://github.com/pyopensci/metrics
        aria-label: GitHub